server:
  port: 8091

spring:
  zipkin:
    enable: true
    base-url: http://localhost:9411
    service:
      name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: 3462
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


rabbitmq:
  queueRegister: register-queue